/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: vendor/huawei/chipset_common/devkit/lcdkit/tools 
 *---------------------------------------------------------------------------*/

#ifndef _LCDKIT_EFFECT__H_
#define _LCDKIT_EFFECT__H_


#include "plat_effect_para.h"

#include "cdy_boe_ft8719_6p5.h"

#include "cdy_csot_nt36682a_6p5.h"

#include "cdy_tm_nt36682a_6p5.h"

#include "cdy_boe_td4320_6p5.h"

#include "cdl_290_202_6p5.h"

#include "cdl_110_202_6p5.h"

#include "cdl_190_101_6p5.h"

/*---------------------------------------------------------------------------*/
/* static panel selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
BMH_SAMSUNG_EA8076_6P53_PANEL,
BMH_EDO_RM692D9_6P53_PANEL,
TEL_TCL_NT36682C_6P63_PANEL,
TEL_INX_FT8720_6P63_PANEL,
TEL_TM_NT36682C_6P63_PANEL,
TEL_BOE_NT36682C_6P63_PANEL,
TEL_INX_NT36682C_6P63_PANEL,
TEL_BOE_FT8720_6P63_PANEL,
TEL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
TELPRO_TCL_NT36682C_6P63_PANEL,
TELPRO_INX_FT8720_6P63_PANEL,
TELPRO_TM_NT36682C_6P63_PANEL,
TELPRO_BOE_NT36682C_6P63_PANEL,
TELPRO_INX_NT36682C_6P63_PANEL,
TELPRO_BOE_FT8720_6P63_PANEL,
TELPRO_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
JER_BOE_NT37700P_6P57_PANEL,
JER_BOE_EW813P_6P57_PANEL,
JER_VISI_NT37700C_6P57_PANEL,
JER_VISI_NT37700C_6P57_ON_PANEL,
CDY_BOE_FT8719_6P5_PANEL,
CDY_CSOT_NT36682A_6P5_PANEL,
CDY_TM_NT36682A_6P5_PANEL,
CDY_BOE_TD4320_6P5_PANEL,
JEF_SAMSUNG_EA8076_6P53_PANEL,
JEF_EDO_RM692D9_6P53_PANEL,
MXW_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
MXW_TCL_TD4320B_6P497_PANEL,
MXW_TM_NT36682A_6P497_PANEL,
FRL_TCL_NT36682C_6P63_PANEL,
FRL_INX_FT8720_6P63_PANEL,
FRL_TM_NT36682C_6P63_PANEL,
FRL_BOE_NT36682C_6P63_PANEL,
FRL_INX_NT36682C_6P63_PANEL,
FRL_BOE_FT8720_6P63_PANEL,
FRL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
KRJ_BOE_HX83102H_10P3_PANEL,
KRJ_INX_HX83102H_10P3_PANEL,
KRJ_CSOT_NT36523_10P3_PANEL,
KRJ_BOE_NT36523_10P3_PANEL,
KRJ_BL_CSOT_NT36523_10P3_PANEL,
KRJ_BL_BOE_NT36523_10P3_PANEL,
KRJ_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
KRJ_BL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
CDL_290_202_6P5_PANEL,
CDL_110_202_6P5_PANEL,
CDL_190_101_6P5_PANEL,
JSC_090_703_6P53_PANEL,
ANG_190_207_6P57_PANEL,
ANG_310_207_6P57_PANEL,
ANG_191_207_6P57_PANEL,
ANG_310_C01_6P57_PANEL,
BRQ_190_207_6P72_PANEL,
BRQ_310_207_6P72_PANEL,
BRQ_190_D00_6P72_PANEL,
BRQ_310_C00_6P72_PANEL,
INVALID_PANEL_ID,
};


/*---------------------------------------------------------------------------*/
/* static panel board mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct lcd_kit_board_map {
    uint8_t lcd_id;
    char *panel_compatible;
    uint32_t product_id;
};

static struct lcd_kit_board_map lcd_kit_map[] = {
    {DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {BMH_SAMSUNG_EA8076_6P53_PANEL, "samsung_ea8076_6p53_1080p_cmd", 1000},
    {BMH_EDO_RM692D9_6P53_PANEL, "edo_rm692d9_6p53_1080p_cmd", 1000},
    {TEL_TCL_NT36682C_6P63_PANEL, "tcl_nt36682c_6p63_1080p_video", 2000},
    {TEL_INX_FT8720_6P63_PANEL, "inx_ft8720_6p63_1080p_video", 2000},
    {TEL_TM_NT36682C_6P63_PANEL, "tm_nt36682c_6p63_1080p_video", 2000},
    {TEL_BOE_NT36682C_6P63_PANEL, "boe_nt36682c_6p63_1080p_video", 2000},
    {TEL_INX_NT36682C_6P63_PANEL, "inx_nt36682c_6p63_1080p_video", 2000},
    {TEL_BOE_FT8720_6P63_PANEL, "boe_ft8720_6p63_1080p_video", 2000},
    {TEL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {TELPRO_TCL_NT36682C_6P63_PANEL, "tcl_nt36682c_6p63_1080p_video", 2100},
    {TELPRO_INX_FT8720_6P63_PANEL, "inx_ft8720_6p63_1080p_video", 2100},
    {TELPRO_TM_NT36682C_6P63_PANEL, "tm_nt36682c_6p63_1080p_video", 2100},
    {TELPRO_BOE_NT36682C_6P63_PANEL, "boe_nt36682c_6p63_1080p_video", 2100},
    {TELPRO_INX_NT36682C_6P63_PANEL, "inx_nt36682c_6p63_1080p_video", 2100},
    {TELPRO_BOE_FT8720_6P63_PANEL, "boe_ft8720_6p63_1080p_video", 2100},
    {TELPRO_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {JER_BOE_NT37700P_6P57_PANEL, "boe_nt37700p_6p57", 3000},
    {JER_BOE_EW813P_6P57_PANEL, "boe_ew813p_6p57", 3000},
    {JER_VISI_NT37700C_6P57_PANEL, "visi_nt37700c_6p57", 3000},
    {JER_VISI_NT37700C_6P57_ON_PANEL, "visi_nt37700c_6p57_on", 3000},
    {CDY_BOE_FT8719_6P5_PANEL, "boe_ft8719_6p5", 4000},
    {CDY_CSOT_NT36682A_6P5_PANEL, "csot_nt36682a_6p5", 4000},
    {CDY_TM_NT36682A_6P5_PANEL, "tm_nt36682a_6p5", 4000},
    {CDY_BOE_TD4320_6P5_PANEL, "boe_td4320_6p5", 4000},
    {JEF_SAMSUNG_EA8076_6P53_PANEL, "samsung_ea8076_6p53_1080p_cmd", 5000},
    {JEF_EDO_RM692D9_6P53_PANEL, "edo_rm692d9_6p53_1080p_cmd", 5000},
    {MXW_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {MXW_TCL_TD4320B_6P497_PANEL, "tcl_td4320b_6p497_1080p_video", 6000},
    {MXW_TM_NT36682A_6P497_PANEL, "tm_nt36682a_6p497_1080p_video", 6000},
    {FRL_TCL_NT36682C_6P63_PANEL, "tcl_nt36682c_6p63_1080p_video", 7000},
    {FRL_INX_FT8720_6P63_PANEL, "inx_ft8720_6p63_1080p_video", 7000},
    {FRL_TM_NT36682C_6P63_PANEL, "tm_nt36682c_6p63_1080p_video", 7000},
    {FRL_BOE_NT36682C_6P63_PANEL, "boe_nt36682c_6p63_1080p_video", 7000},
    {FRL_INX_NT36682C_6P63_PANEL, "inx_nt36682c_6p63_1080p_video", 7000},
    {FRL_BOE_FT8720_6P63_PANEL, "boe_ft8720_6p63_1080p_video", 7000},
    {FRL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {KRJ_BOE_HX83102H_10P3_PANEL, "boe_hx83102h_10p3", 8000},
    {KRJ_INX_HX83102H_10P3_PANEL, "inx_hx83102h_10p3", 8000},
    {KRJ_CSOT_NT36523_10P3_PANEL, "csot_nt36523_10p3", 8000},
    {KRJ_BOE_NT36523_10P3_PANEL, "boe_nt36523_10p3", 8000},
    {KRJ_BL_CSOT_NT36523_10P3_PANEL, "csot_nt36523_10p3", 8001},
    {KRJ_BL_BOE_NT36523_10P3_PANEL, "boe_nt36523_10p3", 8001},
    {KRJ_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {KRJ_BL_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {CDL_290_202_6P5_PANEL, "290_202_6p5", 12000},
    {CDL_110_202_6P5_PANEL, "110_202_6p5", 12000},
    {CDL_190_101_6P5_PANEL, "190_101_6p5", 12000},
    {JSC_090_703_6P53_PANEL, "090_703_6p53", 9000},
    {ANG_190_207_6P57_PANEL, "190_207_6p57", 10000},
    {ANG_310_207_6P57_PANEL, "310_207_6p57", 10000},
    {ANG_191_207_6P57_PANEL, "191_207_6p57", 10000},
    {ANG_310_C01_6P57_PANEL, "310_c01_6p57", 10000},
    {BRQ_190_207_6P72_PANEL, "190_207_6p72", 11000},
    {BRQ_310_207_6P72_PANEL, "310_207_6p72", 11000},
    {BRQ_190_D00_6P72_PANEL, "190_d00_6p72", 11000},
    {BRQ_310_C00_6P72_PANEL, "310_c00_6p72", 11000},
};

static void lcd_kit_effect_get_data(uint8_t panel_id, struct hisi_panel_info* pinfo)
{
    if (pinfo->gamma_support == 1)
    {
        pinfo->gamma_lut_table_R = plat_gamma_lut_table_R;
        pinfo->gamma_lut_table_G = plat_gamma_lut_table_G;
        pinfo->gamma_lut_table_B = plat_gamma_lut_table_B;
        pinfo->gamma_lut_table_len = ARRAY_SIZE(plat_gamma_lut_table_R);
        pinfo->igm_lut_table_R = plat_igm_lut_table_R;
        pinfo->igm_lut_table_G = plat_igm_lut_table_G;
        pinfo->igm_lut_table_B = plat_igm_lut_table_B;
        pinfo->igm_lut_table_len = ARRAY_SIZE(plat_igm_lut_table_R);
        pinfo->gmp_lut_table_low32bit = &plat_gmp_lut_table_low32bit[0][0][0];
        pinfo->gmp_lut_table_high4bit = &plat_gmp_lut_table_high4bit[0][0][0];
        pinfo->gmp_lut_table_len = ARRAY_3_SIZE(plat_gmp_lut_table_low32bit);
        pinfo->xcc_table = plat_xcc_table;
        pinfo->xcc_table_len = ARRAY_SIZE(plat_xcc_table);
    }
    switch (panel_id) {
    case CDY_BOE_FT8719_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdy_boe_ft8719_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdy_boe_ft8719_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdy_boe_ft8719_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdy_boe_ft8719_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdy_boe_ft8719_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdy_boe_ft8719_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdy_boe_ft8719_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdy_boe_ft8719_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdy_boe_ft8719_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdy_boe_ft8719_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdy_boe_ft8719_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdy_boe_ft8719_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdy_boe_ft8719_6p5_xcc_table);
        }
        break;
    case CDY_CSOT_NT36682A_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdy_csot_nt36682a_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdy_csot_nt36682a_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdy_csot_nt36682a_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdy_csot_nt36682a_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdy_csot_nt36682a_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdy_csot_nt36682a_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdy_csot_nt36682a_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdy_csot_nt36682a_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdy_csot_nt36682a_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdy_csot_nt36682a_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdy_csot_nt36682a_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdy_csot_nt36682a_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdy_csot_nt36682a_6p5_xcc_table);
        }
        break;
    case CDY_TM_NT36682A_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdy_tm_nt36682a_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdy_tm_nt36682a_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdy_tm_nt36682a_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdy_tm_nt36682a_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdy_tm_nt36682a_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdy_tm_nt36682a_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdy_tm_nt36682a_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdy_tm_nt36682a_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdy_tm_nt36682a_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdy_tm_nt36682a_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdy_tm_nt36682a_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdy_tm_nt36682a_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdy_tm_nt36682a_6p5_xcc_table);
        }
        break;
    case CDY_BOE_TD4320_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdy_boe_td4320_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdy_boe_td4320_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdy_boe_td4320_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdy_boe_td4320_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdy_boe_td4320_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdy_boe_td4320_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdy_boe_td4320_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdy_boe_td4320_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdy_boe_td4320_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdy_boe_td4320_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdy_boe_td4320_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdy_boe_td4320_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdy_boe_td4320_6p5_xcc_table);
        }
        break;
    case CDL_290_202_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdl_290_202_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdl_290_202_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdl_290_202_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdl_290_202_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdl_290_202_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdl_290_202_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdl_290_202_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdl_290_202_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdl_290_202_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdl_290_202_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdl_290_202_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdl_290_202_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdl_290_202_6p5_xcc_table);
        }
        break;
    case CDL_110_202_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdl_110_202_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdl_110_202_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdl_110_202_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdl_110_202_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdl_110_202_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdl_110_202_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdl_110_202_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdl_110_202_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdl_110_202_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdl_110_202_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdl_110_202_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdl_110_202_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdl_110_202_6p5_xcc_table);
        }
        break;
    case CDL_190_101_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdl_190_101_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdl_190_101_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdl_190_101_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdl_190_101_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdl_190_101_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdl_190_101_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdl_190_101_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdl_190_101_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdl_190_101_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdl_190_101_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdl_190_101_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdl_190_101_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdl_190_101_6p5_xcc_table);
        }
        break;
    default:
        LCD_KIT_INFO("Panel ID not detected %d\n", panel_id);
        break;
    }
}

static uint8_t lcd_kit_get_panel_id(uint32_t product_id, char* compatible)
{
    uint8_t lcd_panel_id = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL;
    int i = 0;
    int len = strlen(compatible);
    int length = 0;
    for (i = 0; i < ARRAY_SIZE(lcd_kit_map); ++i) {
        length = strlen(lcd_kit_map[i].panel_compatible);
        if ((lcd_kit_map[i].product_id == product_id) && !strncmp(lcd_kit_map[i].panel_compatible, compatible, (length > len?length:len))){
            lcd_panel_id = lcd_kit_map[i].lcd_id;
            break;
        }
    }

    HISI_FB_INFO("lcd_panel_id = %d\n", lcd_panel_id);
    return lcd_panel_id;
}


#endif /*_LCDKIT_EFFECT__H_*/
