#ifndef __SOC_MID_H__
#define __SOC_MID_H__ 
#define SOC_LPMCU_MID 0x00
#define SOC_IOMCU_M7_MID 0x01
#define SOC_PERF_STAT_LATMON_MID 0x03
#define SOC_IPF_MID 0x04
#define SOC_DJTAG_M_TOP_CSSYS_MID 0x05
#define SOC_IOMCU_DMA_AO_TCP_MID 0x06
#define SOC_UFS_MID 0x07
#define SOC_SD_MID 0x08
#define SOC_SDIO_MID 0x09
#define SOC_CC712_MID 0x0a
#define SOC_FD_UL_MID 0x0b
#define SOC_DPC_MID 0x0c
#define SOC_SOCP_MID 0x0d
#define SOC_USB31OTG_MID 0x0e
#define SOC_MODEM_CPU5G_EICC1_EICC_MID 0x0f
#define SOC_DMAC_MID 0x10
#define SOC_ASP_HIFI_MID 0x11
#define SOC_PCIE_0_MID 0x12
#define SOC_ATGS_MID 0x13
#define SOC_ASP_DMA_USB_HDMI_MID 0x14
#define SOC_MODEM_MAA_MID 0x15
#define SOC_MODEM_L2CPU_CFG_L2CPU_L2C_MID 0x20
#define SOC_MODEM_L2HAC_CIPHER_MID 0x21
#define SOC_MODEM_LATENCY_MONITOR_MID 0x22
#define SOC_MODEM_CPU5G_CFG_CPU5G_L2C_MID 0x23
#define SOC_MODEM_SPE_MID 0x24
#define SOC_MODEM_L2HAC_EICC0_MID 0x25
#define SOC_MODEM_L2HAC_EICC1_MID 0x26
#define SOC_MODEM_LL1C_BBE0_MID 0x27
#define SOC_MODEM_LL1C_BBE1_MID 0x28
#define SOC_MODEM_LL1C_EDMA0_MID 0x29
#define SOC_MODEM_LL1C_EDMA1_MID 0x2a
#define SOC_MODEM_LL1C_EICC0_MID 0x2b
#define SOC_MODEM_LL1C_EICC1_MID 0x2c
#define SOC_MODEM_LL1C_FASTDMA_MID 0x2d
#define SOC_MODEM_BBP5G_FASTDMA_MID 0x2e
#define SOC_MODEM_CPU5G_EICC0_MID 0x2f
#define SOC_MODEM_BBP5G_COMDMA2SOC_MID 0x30
#define SOC_MODEM_BBP5G_COMDMA2DDR_MID 0x31
#define SOC_MODEM_BBP5G_PDE_PDS_MID 0x32
#define SOC_MODEM_BBP5G_PDE_CSI_MID 0x33
#define SOC_MODEM_BBIC_MID 0x34
#define SOC_MODEM_BBP5G_NLDL2SOC_MID 0x35
#define SOC_MODEM_CIPHER_MID 0x16
#define SOC_MODEM_HDLC_MID 0x36
#define SOC_MODEM_CICOM0_MID 0x17
#define SOC_MODEM_CICOM1_MID 0x37
#define SOC_MODEM_LL1C_BBE2_NXDSP_MID 0x18
#define SOC_MODEM_BBP5G_NLDL2DDR_MID 0x38
#define SOC_MODEM_TL_BBP_DMA_TCM_MID 0x19
#define SOC_MODEM_TL_BBP_DMA_DDR_MID 0x39
#define SOC_MODEM_GU_BBP_MST_TCM_MID 0x1a
#define SOC_MODEM_GU_BBP_MST_DDR_MID 0x3a
#define SOC_MODEM_MDM5G_EDMA0_EDMA0_MID 0x1b
#define SOC_MODEM_MDM5G_EDMA1_EDMA1_MID 0x3b
#define SOC_MODEM_BBP5G_UL_HARQ_L_MID 0x1c
#define SOC_MODEM_HARQ_H_MID 0x3c
#define SOC_MODEM_UPACC_MID 0x1d
#define SOC_MODEM_MDM5G_RSR_ACC_RSR_ACC_MID 0x3d
#define SOC_MODEM_CIPHER_WRITE_THOUGH_MID 0x1e
#define SOC_MODEM_CCPU_CFG_CCPU_L2C_MID 0x3f
#define SOC_MODEM_EDMA2_MID 0x1f
#define SOC_ISP_1_ISP_CORE_0_MID 0x40
#define SOC_ISP_1_ISP_CORE_1_MID 0x41
#define SOC_ISP_1_ISP_CORE_2_MID 0x42
#define SOC_ISP_1_ISP_CORE_3_MID 0x43
#define SOC_ISP_1_ISP_CORE_4_MID 0x44
#define SOC_ISP_1_ISP_CORE_5_MID 0x45
#define SOC_ISP_1_ISP_CORE_6_MID 0x46
#define SOC_ISP_1_ISP_CORE_7_MID 0x47
#define SOC_ISP_2_ISP_CORE_0_MID 0x48
#define SOC_ISP_2_ISP_CORE_1_MID 0x49
#define SOC_ISP_2_ISP_CORE_2_MID 0x4a
#define SOC_ISP_2_ISP_CORE_3_MID 0x4b
#define SOC_DSS_CMDLIST_MID 0x50
#define SOC_DSS_WR_1_MID 0x51
#define SOC_DSS_WR_0_MID 0x52
#define SOC_DSS_RD_7_MID 0x54
#define SOC_DSS_RD_6_MID 0x55
#define SOC_DSS_RD_5_MID 0x56
#define SOC_DSS_RD_4_MID 0x57
#define SOC_DSS_RD_3_MID 0x58
#define SOC_DSS_RD_2_MID 0x59
#define SOC_DSS_RD_0_DSS_ATGM_MID 0x5b
#define SOC_IPP_SUBSYS_JPGENC_MID 0x5d
#define SOC_VENC_0_MID 0x60
#define SOC_VENC_1_MID 0x61
#define SOC_VDEC1_VDEC_MID 0x62
#define SOC_VDEC2_MID 0x63
#define SOC_VDEC3_MID 0x64
#define SOC_VDEC4_MID 0x65
#define SOC_VDEC5_MID 0x66
#define SOC_VDEC6_MID 0x67
#define SOC_IVP32_DSP_DSP_CORE_INST_IVP_ATGM_MID 0x69
#define SOC_IVP32_DSP_DSP_CORE_INST_MID SOC_IVP32_DSP_DSP_CORE_INST_IVP_ATGM_MID
#define SOC_IVP32_DSP_DSP_DMA_MID 0x6a
#define SOC_ISP_ISP_A7_CFG_MID 0x6b
#define SOC_IPP_SUBSYS_CPE_MID 0x6e
#define SOC_IPP_SUBSYS_SLAM_MID 0x6f
#define SOC_NPU0_MID 0x70
#define SOC_NPU1_MID 0x71
#define SOC_IVP32_DSP_DSP_CORE_DATA_MID 0x74
#define SOC_FCM_MID 0x78
#define SOC_FCM_RSV_MID 0x79
#define SOC_GPU0_NON_DRM_MID 0x7a
#define SOC_GPU0_DRM_MID 0x7b
#define SOC_IDI2AXI_MID 0x7c
#define SOC_MAX_MID 0x7D
#define SEC_ASI0_MASK 0x1F
#define SEC_ASI12_MASK 0x1F
#define SEC_ASI34_MASK 0x1F
#define SEC_ASI5_MASK 0x1F
#define SEC_ASI67_MASK 0x1
#define SEC_ASI89_MASK 0x1
#define SEC_ASIA_MASK 0x1F
#define SEC_ASIB_MASK 0x1F
#define SEC_ASIC_MASK 0x1F
#define SEC_ASID_MASK 0x1
#define TZMP2_ASI0_MASK 0x1F
#define TZMP2_ASI12_MASK 0x1F
#define TZMP2_ASI34_MASK 0x1F
#define TZMP2_ASI5_MASK 0x3F
#define TZMP2_ASI67_MASK 0x1F
#define TZMP2_ASI89_MASK 0x1F
#define TZMP2_ASIA_MASK 0x1F
#define TZMP2_ASIB_MASK 0x1F
#define TZMP2_ASIC_MASK 0x1F
#define TZMP2_ASID_MASK 0x1F
#define SEC_BIT(n) (1U << (n))
#define ASI0_MODEM_CPU5G_CFG_CPU5G_L2C_MID (SOC_MODEM_CPU5G_CFG_CPU5G_L2C_MID & SEC_ASI0_MASK)
#define MODEM_BBP5G_FASTDMA_MID (SOC_MODEM_BBP5G_FASTDMA_MID & SEC_ASI0_MASK)
#define MODEM_BBP5G_COMDMA2SOC_MID (SOC_MODEM_BBP5G_COMDMA2SOC_MID & SEC_ASI0_MASK)
#define MODEM_BBP5G_COMDMA2DDR_MID (SOC_MODEM_BBP5G_COMDMA2DDR_MID & SEC_ASI0_MASK)
#define MODEM_BBP5G_PDE_PDS_MID (SOC_MODEM_BBP5G_PDE_PDS_MID & SEC_ASI0_MASK)
#define MODEM_BBP5G_PDE_CSI_MID (SOC_MODEM_BBP5G_PDE_CSI_MID & SEC_ASI0_MASK)
#define ASI0_MODEM_BBIC_MID (SOC_MODEM_BBIC_MID & SEC_ASI0_MASK)
#define MODEM_BBP5G_NLDL2SOC_MID (SOC_MODEM_BBP5G_NLDL2SOC_MID & SEC_ASI0_MASK)
#define MODEM_BBP5G_UL_HARQ_L_MID (SOC_MODEM_BBP5G_UL_HARQ_L_MID & SEC_ASI0_MASK)
#define ASI0_MODEM_SUBSYS_NOAP (SEC_BIT(ASI0_MODEM_CPU5G_CFG_CPU5G_L2C_MID) | SEC_BIT(MODEM_BBP5G_FASTDMA_MID) | \
 SEC_BIT(MODEM_BBP5G_COMDMA2DDR_MID) | SEC_BIT(MODEM_BBP5G_PDE_PDS_MID) | \
 SEC_BIT(MODEM_BBP5G_PDE_CSI_MID) | SEC_BIT(ASI0_MODEM_BBIC_MID) | SEC_BIT(MODEM_BBP5G_UL_HARQ_L_MID))
#define ASI0_MODEM_SUBSYS_AP 0
#define ASI0_MODEM_SUBSYS_NO (SEC_BIT(MODEM_BBP5G_COMDMA2SOC_MID) | SEC_BIT(MODEM_BBP5G_NLDL2SOC_MID))
#define VENC_0_MID (SOC_VENC_0_MID & SEC_ASI12_MASK)
#define VENC_1_MID (SOC_VENC_1_MID & SEC_ASI12_MASK)
#define VDEC1_MID (SOC_VDEC1_VDEC_MID & SEC_ASI12_MASK)
#define VDEC2_MID (SOC_VDEC2_MID & SEC_ASI12_MASK)
#define VDEC3_MID (SOC_VDEC3_MID & SEC_ASI12_MASK)
#define VDEC4_MID (SOC_VDEC4_MID & SEC_ASI12_MASK)
#define VDEC5_MID (SOC_VDEC5_MID & SEC_ASI12_MASK)
#define VDEC6_MID (SOC_VDEC6_MID & SEC_ASI12_MASK)
#define VENC_ALL (SEC_BIT(VENC_0_MID) | SEC_BIT(VENC_1_MID))
#define VDEC_ALL (SEC_BIT(VDEC1_MID) | SEC_BIT(VDEC2_MID) | SEC_BIT(VDEC3_MID) | SEC_BIT(VDEC4_MID) | \
                         SEC_BIT(VDEC5_MID) | SEC_BIT(VDEC6_MID))
#define IVP32_DSP_DSP_CORE_INST_MID (SOC_IVP32_DSP_DSP_CORE_INST_IVP_ATGM_MID & SEC_ASI12_MASK)
#define IVP32_DSP_DSP_DMA_MID (SOC_IVP32_DSP_DSP_DMA_MID & SEC_ASI12_MASK)
#define IVP32_DSP_DSP_CORE_DATA_MID (SOC_IVP32_DSP_DSP_CORE_DATA_MID & SEC_ASI12_MASK)
#define IVP_ALL (SEC_BIT(IVP32_DSP_DSP_CORE_INST_MID) | SEC_BIT(IVP32_DSP_DSP_DMA_MID) | SEC_BIT(IVP32_DSP_DSP_CORE_DATA_MID))
#define ISP_1_ISP_CORE_0_MID (SOC_ISP_1_ISP_CORE_0_MID & SEC_ASI34_MASK)
#define ISP_1_ISP_CORE_1_MID (SOC_ISP_1_ISP_CORE_1_MID & SEC_ASI34_MASK)
#define ISP_1_ISP_CORE_2_MID (SOC_ISP_1_ISP_CORE_2_MID & SEC_ASI34_MASK)
#define ISP_1_ISP_CORE_3_MID (SOC_ISP_1_ISP_CORE_3_MID & SEC_ASI34_MASK)
#define ISP_1_ISP_CORE_4_MID (SOC_ISP_1_ISP_CORE_4_MID & SEC_ASI34_MASK)
#define ISP_1_ISP_CORE_5_MID (SOC_ISP_1_ISP_CORE_5_MID & SEC_ASI34_MASK)
#define ISP_1_ISP_CORE_6_MID (SOC_ISP_1_ISP_CORE_6_MID & SEC_ASI34_MASK)
#define ISP_1_ISP_CORE_7_MID (SOC_ISP_1_ISP_CORE_7_MID & SEC_ASI34_MASK)
#define ISP_2_ISP_CORE_0_MID (SOC_ISP_2_ISP_CORE_0_MID & SEC_ASI34_MASK)
#define ISP_2_ISP_CORE_1_MID (SOC_ISP_2_ISP_CORE_1_MID & SEC_ASI34_MASK)
#define ISP_2_ISP_CORE_2_MID (SOC_ISP_2_ISP_CORE_2_MID & SEC_ASI34_MASK)
#define ISP_2_ISP_CORE_3_MID (SOC_ISP_2_ISP_CORE_3_MID & SEC_ASI34_MASK)
#define DSS_CMDLIST_MID (SOC_DSS_CMDLIST_MID & SEC_ASI34_MASK)
#define DSS_WR_1_MID (SOC_DSS_WR_1_MID & SEC_ASI34_MASK)
#define DSS_WR_0_MID (SOC_DSS_WR_0_MID & SEC_ASI34_MASK)
#define DSS_RD_7_MID (SOC_DSS_RD_7_MID & SEC_ASI34_MASK)
#define DSS_RD_6_MID (SOC_DSS_RD_6_MID & SEC_ASI34_MASK)
#define DSS_RD_5_MID (SOC_DSS_RD_5_MID & SEC_ASI34_MASK)
#define DSS_RD_4_MID (SOC_DSS_RD_4_MID & SEC_ASI34_MASK)
#define DSS_RD_3_MID (SOC_DSS_RD_3_MID & SEC_ASI34_MASK)
#define DSS_RD_2_MID (SOC_DSS_RD_2_MID & SEC_ASI34_MASK)
#define DSS_RD_0_MID (SOC_DSS_RD_0_DSS_ATGM_MID & SEC_ASI34_MASK)
#define ISP_ALL (SEC_BIT(ISP_1_ISP_CORE_0_MID) | SEC_BIT(ISP_1_ISP_CORE_1_MID) | SEC_BIT(ISP_1_ISP_CORE_2_MID) | SEC_BIT(ISP_1_ISP_CORE_3_MID) | \
                                 SEC_BIT(ISP_1_ISP_CORE_4_MID) | SEC_BIT(ISP_1_ISP_CORE_5_MID) | SEC_BIT(ISP_1_ISP_CORE_6_MID) | SEC_BIT(ISP_1_ISP_CORE_7_MID) | \
                                 SEC_BIT(ISP_2_ISP_CORE_0_MID) | SEC_BIT(ISP_2_ISP_CORE_1_MID) | SEC_BIT(ISP_2_ISP_CORE_2_MID) | SEC_BIT(ISP_2_ISP_CORE_3_MID))
#define DSS_ALL (SEC_BIT(DSS_CMDLIST_MID) | SEC_BIT(DSS_WR_1_MID) | SEC_BIT(DSS_WR_0_MID) | \
                                 SEC_BIT(DSS_RD_7_MID) | SEC_BIT(DSS_RD_6_MID) | SEC_BIT(DSS_RD_5_MID) | SEC_BIT(DSS_RD_4_MID) | \
                                 SEC_BIT(DSS_RD_3_MID) | SEC_BIT(DSS_RD_2_MID) | SEC_BIT(DSS_RD_0_MID))
#define IPP_SUBSYS_JPGENC_MID (SOC_IPP_SUBSYS_JPGENC_MID & SEC_ASI34_MASK)
#define IPP_SUBSYS_CPE_MID (SOC_IPP_SUBSYS_CPE_MID & SEC_ASI34_MASK)
#define IPP_SUBSYS_SLAM_MID (SOC_IPP_SUBSYS_SLAM_MID & SEC_ASI34_MASK)
#define IPP_SUBSYS_ALL (SEC_BIT(IPP_SUBSYS_JPGENC_MID) | SEC_BIT(IPP_SUBSYS_CPE_MID) | SEC_BIT(IPP_SUBSYS_SLAM_MID))
#define IDI2AXI_MID (SOC_IDI2AXI_MID & SEC_ASI34_MASK)
#define LPMCU_MID (SOC_LPMCU_MID & SEC_ASI5_MASK)
#define IOMCU_M7_MID (SOC_IOMCU_M7_MID & SEC_ASI5_MASK)
#define PERF_STAT_LATMON_MID (SOC_PERF_STAT_LATMON_MID & SEC_ASI5_MASK)
#define MODEM_IPF_MID (SOC_IPF_MID & SEC_ASI5_MASK)
#define DJTAG_M_TOP_CSSYS_MID (SOC_DJTAG_M_TOP_CSSYS_MID & SEC_ASI5_MASK)
#define IOMCU_DMA_AO_TCP_MID (SOC_IOMCU_DMA_AO_TCP_MID & SEC_ASI5_MASK)
#define UFS_MID (SOC_UFS_MID & SEC_ASI5_MASK)
#define SD_MID (SOC_SD_MID & SEC_ASI5_MASK)
#define SDIO_MID (SOC_SDIO_MID & SEC_ASI5_MASK)
#define CC712_MID (SOC_CC712_MID & SEC_ASI5_MASK)
#define FD_UL_MID (SOC_FD_UL_MID & SEC_ASI5_MASK)
#define DPC_MID (SOC_DPC_MID & SEC_ASI5_MASK)
#define MODEM_SOCP_MID (SOC_SOCP_MID & SEC_ASI5_MASK)
#define USB31OTG_MID (SOC_USB31OTG_MID & SEC_ASI5_MASK)
#define ASI5_MODEM_CPU5G_EICC1_EICC_MID (SOC_MODEM_CPU5G_EICC1_EICC_MID & SEC_ASI5_MASK)
#define DMAC_MID (SOC_DMAC_MID & SEC_ASI5_MASK)
#define ASP_HIFI_MID (SOC_ASP_HIFI_MID & SEC_ASI5_MASK)
#define PCIE_0_MID (SOC_PCIE_0_MID & SEC_ASI5_MASK)
#define ATGS_MID (SOC_ATGS_MID & SEC_ASI5_MASK)
#define ASP_DMA_MID (SOC_ASP_DMA_USB_HDMI_MID & SEC_ASI5_MASK)
#define MODEM_MAA_MID (SOC_MODEM_MAA_MID & SEC_ASI5_MASK)
#define MODEM_SPE_MID (SOC_MODEM_SPE_MID & SEC_ASI5_MASK)
#define MODEM_CIPHER_MID (SOC_MODEM_CIPHER_MID & SEC_ASI5_MASK)
#define MODEM_HDLC_MID (SOC_MODEM_HDLC_MID & SEC_ASI5_MASK)
#define MODEM_CICOM0_MID (SOC_MODEM_CICOM0_MID & SEC_ASI5_MASK)
#define MODEM_CICOM1_MID (SOC_MODEM_CICOM1_MID & SEC_ASI5_MASK)
#define MODEM_TL_BBP_DMA_TCM_MID (SOC_MODEM_TL_BBP_DMA_TCM_MID & SEC_ASI5_MASK)
#define MODEM_TL_BBP_DMA_DDR_MID (SOC_MODEM_TL_BBP_DMA_DDR_MID & SEC_ASI5_MASK)
#define MODEM_GU_BBP_MST_TCM_MID (SOC_MODEM_GU_BBP_MST_TCM_MID & SEC_ASI5_MASK)
#define MODEM_GU_BBP_MST_DDR_MID (SOC_MODEM_GU_BBP_MST_DDR_MID & SEC_ASI5_MASK)
#define ASI5_MODEM_MDM5G_EDMA0_EDMA0_MID (SOC_MODEM_MDM5G_EDMA0_EDMA0_MID & SEC_ASI5_MASK)
#define ASI5_MODEM_MDM5G_EDMA1_EDMA1_MID (SOC_MODEM_MDM5G_EDMA1_EDMA1_MID & SEC_ASI5_MASK)
#define ASI5_MODEM_BBP5G_UL_HARQ_L_MID (SOC_MODEM_BBP5G_UL_HARQ_L_MID & SEC_ASI5_MASK)
#define ASI5_MODEM_HARQ_H_MID (SOC_MODEM_HARQ_H_MID & SEC_ASI5_MASK)
#define MODEM_UPACC_MID (SOC_MODEM_UPACC_MID & SEC_ASI5_MASK)
#define ASI5_MODEM_MDM5G_RSR_ACC_RSR_ACC_MID (SOC_MODEM_MDM5G_RSR_ACC_RSR_ACC_MID & SEC_ASI5_MASK)
#define MODEM_CIPHER_WRITE_THOUGH_MID (SOC_MODEM_CIPHER_WRITE_THOUGH_MID & SEC_ASI5_MASK)
#define ASI5_MODEM_CCPU_CFG_CCPU_L2C_MID (SOC_MODEM_CCPU_CFG_CCPU_L2C_MID & SEC_ASI5_MASK)
#define MODEM_EDMA2_MID (SOC_MODEM_EDMA2_MID & SEC_ASI5_MASK)
#define ASI5_MODEM_SUBSYS_NOAP (SEC_BIT(ASI5_MODEM_CPU5G_EICC1_EICC_MID) | SEC_BIT(MODEM_TL_BBP_DMA_TCM_MID) | \
 SEC_BIT(MODEM_TL_BBP_DMA_DDR_MID) | SEC_BIT(MODEM_GU_BBP_MST_TCM_MID) | \
 SEC_BIT(MODEM_GU_BBP_MST_DDR_MID) | SEC_BIT(ASI5_MODEM_MDM5G_EDMA0_EDMA0_MID) | SEC_BIT(ASI5_MODEM_MDM5G_EDMA1_EDMA1_MID) | \
 SEC_BIT(MODEM_UPACC_MID) | \
 SEC_BIT(ASI5_MODEM_MDM5G_RSR_ACC_RSR_ACC_MID) | SEC_BIT(ASI5_MODEM_CCPU_CFG_CCPU_L2C_MID) | SEC_BIT(MODEM_EDMA2_MID))
#define ASI5_MODEM_SUBSYS_AP (SEC_BIT(IPF_MID) | SEC_BIT(MODEM_SPE_MID) | SEC_BIT(SOCP_MID)| \
 SEC_BIT(MODEM_MAA_MID) | SEC_BIT(MODEM_CIPHER_MID) | SEC_BIT(MODEM_HDLC_MID) | \
 SEC_BIT(MODEM_CICOM0_MID) | SEC_BIT(MODEM_CICOM1_MID) | SEC_BIT(ASI5_MODEM_BBP5G_UL_HARQ_L_MID) | \
 SEC_BIT(ASI5_MODEM_HARQ_H_MID) | SEC_BIT(MODEM_CIPHER_WRITE_THOUGH_MID))
#define CPU_ALL (SEC_BIT((SOC_FCM_MID & SEC_ASI67_MASK)))
#define NPU_ATGM_NPU_MID (SOC_NPU0_MID & SEC_ASI89_MASK)
#define NPU_NPU_MID (SOC_NPU1_MID & SEC_ASI89_MASK)
#define NPU_ALL (SEC_BIT(NPU_ATGM_NPU_MID) | SEC_BIT(NPU_NPU_MID))
#define MODEM_BBP5G_NLDL2DDR_MID (SOC_MODEM_BBP5G_NLDL2DDR_MID & SEC_ASIA_MASK)
#define ASI11_MODEM_BBIC_MID (SOC_MODEM_BBIC_MID & SEC_ASIB_MASK)
#define ASI11_MODEM_LL1C_BBE2_NXDSP_MID (SOC_MODEM_LL1C_BBE2_NXDSP_MID & SEC_ASIB_MASK)
#define ASI11_MODEM_BBP5G_UL_HARQ_L_MID (SOC_MODEM_BBP5G_UL_HARQ_L_MID & SEC_ASIB_MASK)
#define ASI11_MODEM_HARQ_H_MID (SOC_MODEM_HARQ_H_MID & SEC_ASIB_MASK)
#define ASI11_MODEM_CCPU_CFG_CCPU_L2C_MID (SOC_MODEM_CCPU_CFG_CCPU_L2C_MID & SEC_ASIB_MASK)
#define ASI11_MODEM_SUBSYS_NOAP (SEC_BIT(ASI11_MODEM_BBIC_MID) | SEC_BIT(ASI11_MODEM_LL1C_BBE2_NXDSP_MID) | SEC_BIT(ASI11_MODEM_BBP5G_UL_HARQ_L_MID) | \
 SEC_BIT(ASI11_MODEM_HARQ_H_MID) | SEC_BIT(ASI11_MODEM_CCPU_CFG_CCPU_L2C_MID))
#define ASI11_MODEM_SUBSYS_AP 0
#define ASI12_MODEM_CPU5G_EICC1_EICC_MID (SOC_MODEM_CPU5G_EICC1_EICC_MID & SEC_ASIC_MASK)
#define MODEM_L2CPU_CFG_L2CPU_L2C_MID (SOC_MODEM_L2CPU_CFG_L2CPU_L2C_MID & SEC_ASIC_MASK)
#define MODEM_L2HAC_CIPHER_MID (SOC_MODEM_L2HAC_CIPHER_MID & SEC_ASIC_MASK)
#define MODEM_LATENCY_MONITOR_MID (SOC_MODEM_LATENCY_MONITOR_MID & SEC_ASIC_MASK)
#define ASI12_MODEM_CPU5G_CFG_CPU5G_L2C_MID (SOC_MODEM_CPU5G_CFG_CPU5G_L2C_MID & SEC_ASIC_MASK)
#define MODEM_L2HAC_EICC0_MID (SOC_MODEM_L2HAC_EICC0_MID & SEC_ASIC_MASK)
#define MODEM_L2HAC_EICC1_MID (SOC_MODEM_L2HAC_EICC1_MID & SEC_ASIC_MASK)
#define MODEM_LL1C_BBE0_MID (SOC_MODEM_LL1C_BBE0_MID & SEC_ASIC_MASK)
#define MODEM_LL1C_BBE1_MID (SOC_MODEM_LL1C_BBE1_MID & SEC_ASIC_MASK)
#define MODEM_LL1C_EDMA0_MID (SOC_MODEM_LL1C_EDMA0_MID & SEC_ASIC_MASK)
#define MODEM_LL1C_EDMA1_MID (SOC_MODEM_LL1C_EDMA1_MID & SEC_ASIC_MASK)
#define MODEM_LL1C_EICC0_MID (SOC_MODEM_LL1C_EICC0_MID & SEC_ASIC_MASK)
#define MODEM_LL1C_EICC1_MID (SOC_MODEM_LL1C_EICC1_MID & SEC_ASIC_MASK)
#define MODEM_LL1C_FASTDMA_MID (SOC_MODEM_LL1C_FASTDMA_MID & SEC_ASIC_MASK)
#define MODEM_CPU5G_EICC0_MID (SOC_MODEM_CPU5G_EICC0_MID & SEC_ASIC_MASK)
#define ASI12_MODEM_LL1C_BBE2_NXDSP_MID (SOC_MODEM_LL1C_BBE2_NXDSP_MID & SEC_ASIC_MASK)
#define ASI12_MODEM_MDM5G_EDMA0_EDMA0_MID (SOC_MODEM_MDM5G_EDMA0_EDMA0_MID & SEC_ASIC_MASK)
#define ASI12_MODEM_MDM5G_EDMA1_EDMA1_MID (SOC_MODEM_MDM5G_EDMA1_EDMA1_MID & SEC_ASIC_MASK)
#define ASI12_MODEM_MDM5G_RSR_ACC_RSR_ACC_MID (SOC_MODEM_MDM5G_RSR_ACC_RSR_ACC_MID & SEC_ASIC_MASK)
#define MODEM_SUBSYS_NOAP_ASI12 (SEC_BIT(ASI12_MODEM_CPU5G_EICC1_EICC_MID) | \
 SEC_BIT(MODEM_L2CPU_CFG_L2CPU_L2C_MID) | SEC_BIT(ASI12_MODEM_CPU5G_CFG_CPU5G_L2C_MID) | \
 SEC_BIT(MODEM_L2HAC_EICC0_MID) | SEC_BIT(MODEM_L2HAC_EICC1_MID) | \
 SEC_BIT(MODEM_LL1C_EICC0_MID) | SEC_BIT(MODEM_LL1C_EICC1_MID) | SEC_BIT(MODEM_LL1C_FASTDMA_MID) | \
 SEC_BIT(MODEM_CPU5G_EICC0_MID) | SEC_BIT(ASI12_MODEM_LL1C_BBE2_NXDSP_MID) | \
 SEC_BIT(ASI12_MODEM_MDM5G_EDMA0_EDMA0_MID) | SEC_BIT(ASI12_MODEM_MDM5G_EDMA1_EDMA1_MID) | \
 SEC_BIT(ASI12_MODEM_MDM5G_RSR_ACC_RSR_ACC_MID))
#define MODEM_SUBSYS_AP_ASI12 (SEC_BIT(MODEM_L2HAC_CIPHER_MID) | SEC_BIT(MODEM_LL1C_BBE0_MID) | \
 SEC_BIT(MODEM_LL1C_BBE1_MID) | SEC_BIT(MODEM_LL1C_EDMA0_MID) | SEC_BIT(MODEM_LL1C_EDMA1_MID))
#define MODEM_SUBSYS_NO_ASI12 SEC_BIT(MODEM_LATENCY_MONITOR_MID)
#define GPU0_NON_DRM_MID (SOC_GPU0_NON_DRM_MID & SEC_ASID_MASK)
#define GPU0_DRM_MID (SOC_GPU0_DRM_MID & SEC_ASID_MASK)
#define GPU_ALL (SEC_BIT(GPU0_NON_DRM_MID) | SEC_BIT(GPU0_DRM_MID))
#define FORBID_MID (0x0)
#define ALL_MID (0xFFFFFFFF)
#endif
