name: Deploy VitePress site to Pages

on:
  push:
    branches: [KernelSU_on_Huawei]
    paths:
      - 'webside/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'webside/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./webside

      - name: Build with VitePress
        run: npm run docs:build
        working-directory: ./webside

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webside/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4